# -*- coding: utf-8 -*-
#
# This file is part of pytest-invenio.
# Copyright (C) 2017-2019 CERN.
#
# pytest-invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# Docker Compose file for starting an Elasticsearch node and Redis instance.
# These services are needed by some of the tests. Starting the services is as
# simple as running::
#
#   docker-compose up -d

version: '2.2'
services:
  es:
    image: elasticsearch:5
    ports:
      - 9200:9200
  redis:
    image: redis:5
    ports:
      - 6379:6379
