# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2020 CERN.
# Copyright (C) 2022-2024 Graz University of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches:
      - master
      - maint-*
  pull_request:
    branches:
      - master
      - maint-*
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          python-version: [3.9, 3.12]
          requirements-level: [pypi]
          search-service: [opensearch2]
          include:
          - search-service: opensearch2
            SEARCH_EXTRAS: "opensearch2"

    env:
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests,${{ matrix.SEARCH_EXTRAS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Setup Selenium
        run: |
          E2E_OUTPUT=base64
          PATH=$PATH:$HOME/webdrivers
          if [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi

      - name: Install dependencies
        run: |
          pip install ".[$EXTRAS]"
          pip freeze
          docker version


      - name: Run tests
        run: |
          ./run-tests.sh
